logging:
  level.root: WARN
  level.ai.enpasos: DEBUG

muzero:
  activeGame: TICTACTOE
  run: train2
  games:
    TICTACTOE:
      modelName: MuZero-TicTacToe
      gameClassName: ai.enpasos.muzero.tictactoe.config.TicTacToeGame
      actionClassName: ai.enpasos.muzero.tictactoe.config.TicTacToeAction
      playerMode: TWO_PLAYERS
      valueHeadType: DISTRIBUTION  # EXPECTED
      networkWithRewardHead: false
      withRewardHead: false
      numObservationLayers: 3
      numActionLayers: 1
      numChannels: 128
      squeezeChannelRatio: 16  # on squeeze and excitation (SE) block
      numHiddenStateChannels: 5
      numResiduals: 8

      numberOfTrainingStepsPerEpoch: 40

      # windowValueSelfconsistencySize: 5000 <- postponed

      numUnrollSteps: 5
      tdSteps: 9 # size * size
      discount: 1.0
      weightDecay: 0.0001
      valueLossWeight: 1.0
      lrInit: 0.0001
      absorbingStateDropToZero: false # faster for integration test
      visitSoftmaxTemperatureThreshold: 30
      numberTrainingStepsOnStart: 0
      rootDirichletAlpha: 2
      rootExplorationFraction: 0.25
      knownBoundsType: BOARD_GAME
      pbCInit: 1.25
      pbCBase: 19652
      inferenceDeviceType: GPU
      outputDir: ./memory/tictactoe/
      numEpisodes: 1
      size: 3
      maxMoves: 9  # size*size
      boardHeight: 3 # size
      boardWidth: 3 # size
      actionSpaceSize: 9  # size*size

      # without symmetry usage
      # symmetryType: NONE
      # batchSize: 2048

      # using the square symmetry of the board
      symmetryType: SQUARE
      batchSize: 256

      numParallelGamesPlayed: 1000
      gameBufferWritingFormat: ZIPPED_PROTOCOL_BUFFERS # ZIPPED_PROTOCOL_BUFFERS # alternative: ZIPPED_JSON


      # Gumbel MuZero parameters
      initialGumbelM: 4
      cVisit: 10  # 50 in paper
      cScale: 1.0  # 1.0 in paper

      numSimulations: 18
      windowSize: 10000
      numberOfTrainingSteps: 4100
      numPurePolicyPlays: 3
