logging:
  file.name: logs/muzero-tictactoe.log
  pattern:
    console: "%d %-5level %logger{0} : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    root: WARN
    ai.enpasos: DEBUG


muzero:
  activeGame: TICTACTOE
  run: train
  games:
    TICTACTOE:
      modelName: MuZero-TicTacToe
      gameClassName: ai.enpasos.muzero.tictactoe.config.TicTacToeGame
      actionClassName: ai.enpasos.muzero.tictactoe.config.TicTacToeAction
      playerMode: TWO_PLAYERS
      valueHeadType: EXPECTED # DISTRIBUTION
      networkWithRewardHead: false
      withRewardHead: false
      values: [-1,0,1]
      numObservationLayers: 3
      numActionLayers: 1
      squeezeChannelRatio: 16  # on squeeze and excitation (SE) block
      numHiddenStateChannels: 5

      numberOfTrainingStepsPerEpoch: 40

      # windowValueSelfconsistencySize: 5000 <- postponed

      numUnrollSteps: 5
      tdSteps: 9 # size * size
      discount: 1.0
      weightDecay: 0.0001
      valueLossWeight: 1.0
      lrInit: 0.0001
      absorbingStateDropToZero: false # faster for integration test

      numberTrainingStepsOnStart: 0

      knownBoundsType: FROM_VALUES

      inferenceDeviceType: GPU
      outputDir: ./memory/tictactoe/
      numEpisodes: 1
      size: 3
      maxMoves: 9  # size*size
      boardHeight: 3 # size
      boardWidth: 3 # size
      actionSpaceSize: 9  # size*size

      # without symmetry usage
      # symmetryType: NONE
      # batchSize: 2048

      # using the square symmetry of the board
      symmetryType: SQUARE
      batchSize: 256

      numParallelGamesPlayed: 1000
      gameBufferWritingFormat: ZIPPED_PROTOCOL_BUFFERS # alternative: ZIPPED_JSON

      # Gumbel MuZero parameters
      initialGumbelM: 4
      cVisit: 10  # 50 in paper
      cScale: 1.0  # 1.0 in paper

      numSimulations: 20
      windowSize: 10000 # or 20000
      maxGameLiveTime: 20000  # or 40000

      numberOfTrainingSteps: 4000

      numResiduals: 8
      broadcastEveryN: 4
      numChannels: 256
      numBottleneckChannels: 128

      surpriseHandlingOn: false # false in paper
      extraValueTrainingOn: false # false in paper

      temperature: 2.0 # 1.0 -> trust in logits as in paper; infinite -> random distributed = no trust in logits

