/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "muzero"
include(":go")
include(":onnxModelGen")
include(":onnxWithRuntime")
include(":tictactoe")
include(":platform")
include(":pegsolitair")
include(":games")
project(":go").projectDir = file("games/go")
project(":tictactoe").projectDir = file("games/tictactoe")
project(":pegsolitair").projectDir = file("games/pegsolitair")
