logging:
  file.name: logs/muzero-go.log
  pattern:
    console: "%d %-5level %logger{0} : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    root: WARN
    ai.enpasos: INFO

muzero:
  activeGame: GO_5
  run: train
  games:
    GO_5:
      modelName: MuZero-Go-5
      outputDir: ./memory/go5/
      values: [ -25,-24,-23,-22,-21,-20,-19,-18,-17,-16,-15,-14,-13,-12,-11,-10,-9,-8,-7,-6,-5,-4,-3,-2,-1,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25 ]
      komi: 0.5
      maxKomi: 6.5
      size: 5
      boardHeight: 5 # size
      boardWidth: 5 # size
      actionSpaceSize: 26  # size * size + 1,  place a stone on the board or pass


      # general
      gameClassName: ai.enpasos.muzero.go.config.GoGame
      actionClassName: ai.enpasos.muzero.go.config.GoAction
      playerMode: TWO_PLAYERS
      networkWithRewardHead: false
      withRewardHead: false
      absorbingStateDropToZero: false
      inferenceDeviceType: GPU

      # game/environment
      maxMoves: 10000


      # network sizing
      numObservationLayers: 17  # 8 history * 2 player + 1 color of next player
      numActionLayers: 1


      # network training
      symmetryType: SQUARE
      numberOfTrainingStepsPerEpoch: 100
      # windowValueSelfconsistencySize: 30000   <- postponed
      batchSize: 50  # 56
      numUnrollSteps: 5
      # tdSteps: 10000 # here equals max moves
      discount: 1.0
      # loss details
      weightDecay: 0.0001
      # network training - adam optimizer
      lrInit: 0.0001

      # play
      numberTrainingStepsOnStart: 0 # 2000

      knownBoundsType: FROM_VALUES


      gameBufferWritingFormat: ZIPPED_PROTOCOL_BUFFERS # alternative: ZIPPED_JSON


      # Gumbel MuZero parameters
      initialGumbelM: 8
      cVisit: 50  # 50 in paper
      cScale: 1.0  # 1.0 in paper

      numChannels: 256     # 256 in the paper
      numBottleneckChannels: 128
#      numResiduals: 12
#      broadcastEveryN: 8  # broadcasting block in every 8th layer


      numResidualsRepresentation: 12
      broadcastEveryNRepresentation: 8  # out of range here

      numResidualsGeneration: 12
      broadcastEveryNGeneration: 8 # out of range here

      surpriseHandlingOn: false # false in paper
      extraValueTrainingOn: false # false in paper

      valueLossWeight: 1.0

      maxGameLiveTime: 10000000  # or 40000
      surpriseCheckInterval: 50000

      windowSizeStart: 100000
      windowSizeIsDynamic: false

      numberOfTrainingSteps: 300000
    #  numberOfEpisodesPerJVMStart: 40 # 50 would be ok


      numSimMin: 5
      numSimWindow: 5
      numSimMax: 800
      numSimThreshold: 0.001

      numChannelsHiddenLayerSimilarity: 250
      numChannelsOutputLayerSimilarity: 500

      playTypes:
        PLAYOUT:
          forTraining: false
          numSimulations: 50
          rootExplorationFraction: 0.0  # 0.0 means switched off
          temperatureRoot: 0.0
          gumbelActionSelection: false
#        HYBRID:
#          forTraining: true
#          numEpisodes: 1
#          numParallelGamesPlayed: 500
#          tdSteps:  10000
#          forTdStep0ValueTraining: false
#          forTdStep0PolicyTraining: true
#          numSimulations: 30
#          numSimulationsHybrid: 30
#
#          # dirichlet noise on root node helps to explore the game tree where the policy is temporarily underestimating some moves
#          # dirichlet noise is added before mcts
#          rootDirichletAlpha: 0.4
#          rootExplorationFraction: 0.25  # 0.0 means switched off
#
#          # temperatureRoot applies a temperature to the policy target after mcts and after storing it in game statistics but
#          # before drawing the action from the policy target (a little different from the paper)
#          # it helps to explore the game tree where the policy rules out bad moves and makes the agent blind to what could happen after such a move
#          temperatureRoot: 0.8
#          gumbelActionSelection: false

        BEST_EFFORT:
          forTraining: true
          numEpisodes: 2
          numParallelGamesPlayed: 500 #250
          tdSteps: 10000
          numSimulations: 30
          # dirichlet noise on root node helps to explore the game tree where the policy is temporarily underestimating some moves
          # dirichlet noise is added before mcts
          rootDirichletAlpha: 0.4
          rootExplorationFraction: 0.25  # 0.0 means switched off


    GO_9:
      modelName: MuZero-Go-9
      values: [ -25,-24,-23,-22,-21,-20,-19,-18,-17,-16,-15,-14,-13,-12,-11,-10,-9,-8,-7,-6,-5,-4,-3,-2,-1,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25 ]

      outputDir: ./memory/go9/

      komi: 0.5
      maxKomi: 6.5
      size: 9
      boardHeight: 9 # size
      boardWidth: 9 # size
      actionSpaceSize: 82  # size * size + 1,  place a stone on the board or pass
      numChannels: 128
      batchSize: 64
      numParallelGamesPlayed: 100
      numEpisodes: 10

      # general
      gameClassName: ai.enpasos.muzero.go.config.GoGame
      actionClassName: ai.enpasos.muzero.go.config.GoAction
      playerMode: TWO_PLAYERS
      networkWithRewardHead: false
      withRewardHead: false
      absorbingStateDropToZero: false # faster for integration test
      inferenceDeviceType: GPU

      # game/environment
      maxMoves: 10000


      # network sizing
      numObservationLayers: 17  # 8 history * 2 player + 1 color of next player
      numActionLayers: 1

      numResiduals: 16

      # network training
      symmetryType: SQUARE
      numberOfTrainingStepsPerEpoch: 100
      numUnrollSteps: 5
      # tdSteps: 10000 # here equals max moves
      discount: 1.0
      # loss details
      weightDecay: 0.0001
      valueLossWeight: 1.0
      # network training - adam optimizer
      lrInit: 0.0001

      # play
      numberTrainingStepsOnRandomPlay: 0

      knownBoundsType: FROM_VALUES


      gameBufferWritingFormat: ZIPPED_PROTOCOL_BUFFERS # alternative: ZIPPED_JSON


      # Gumbel MuZero parameters
      initialGumbelM: 16
      cVisit: 50  # 50 in paper
      cScale: 1.0  # 1.0 in paper

      numberOfTrainingSteps: 300000


      broadcastEveryN: 8
      numBottleneckChannels: 64


      surpriseHandlingOn: false # false in paper
      extraValueTrainingOn: false # false in paper



      maxGameLiveTime: 10000000  # or 40000
      surpriseCheckInterval: 50000


      windowSizeStart: 50000
      windowSizeIsDynamic: false #
      windowSizeExponent: 0.8  # (sub)linear scaling of window size
      windowSizeSlope: 0.5

      playTypes:
        PLAYOUT:
          forTraining: false
          numSimulations: 50
          rootExplorationFraction: 0.0  # 0.0 means switched off
          temperatureRoot: 0.0
          gumbelActionSelection: false
        HYBRID:
          forTraining: true
          numEpisodes: 2
          numParallelGamesPlayed: 250
          tdSteps:  10000
          forTdStep0NoValueTraining: true
          numSimulations: 50

          # dirichlet noise on root node helps to explore the game tree where the policy is temporarily underestimating some moves
          # dirichlet noise is added before mcts
          rootDirichletAlpha: 0.1
          rootExplorationFraction: 0.25  # 0.0 means switched off

          # temperatureRoot applies a temperature to the policy target after mcts and after storing it in game statistics but
          # before drawing the action from the policy target (a little different from the paper)
          # it helps to explore the game tree where the policy rules out bad moves and makes the agent blind to what could happen after such a move
          temperatureRoot: 2.0
          gumbelActionSelection: false

        BEST_EFFORT:
          numEpisodes: 2
          numParallelGamesPlayed: 250
          tdSteps:  10000
          numSimulations: 50
          rootExplorationFraction: 0.0  # 0.0 means switched off
          gumbelActionSelection: true

