muzero:
  modelName: MuZero-Go-5
  outputDir: ./memory/go5/

  # game/environment
  komi: 0.5
  size: 5
  boardHeight: 5 # size
  boardWidth: 5 # size
  actionSpaceSize: 26  # size * size + 1,  place a stone on the board or pass


  numSimulations: 12
  numParallelGamesPlayed: 250
  numEpisodes: 4

