package ai.enpasos.muzero.platform.config;

public enum RunType {
    NONE, TEST, TRAIN, TRAINFAST, STARTVALUES, VALUE, VALUES, LOSS, RENDER, WINLOOSE, ONNX, INFERENCE, VALUESELFCONSISTENCY, ELO, SURPRISE, SURPRISEEXTRACT, ENTROPY, POLICYONLY
}
