package ai.enpasos.muzero.platform.config;

public enum RunType {
    NONE, BADACTION, INMIND, TEST, TESTNETWORKS, TRAIN, ACTIONS, STARTVALUES, VALUE, VALUES, LOSS, RENDER, ONNX, INFERENCE, ELO, ENTROPY, POLICYONLY
}
