package ai.enpasos.muzero.platform.config;

public enum RunType {
    NONE, FILLVALUETABLE, TEMPERATURE, BADACTION, INMIND, TEST, TESTNETWORKS, TRAIN, ACTIONS, STARTVALUES, ENTROPYVALUE, VALUE, LOSS, RENDER, ONNX, INFERENCE, ELO, ENTROPY,ENTROPY0, POLICYONLY
}
