/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("com.enpasos.muzero.java-conventions")
}

dependencies {
    implementation("com.microsoft.onnxruntime:onnxruntime:1.10.0")
    implementation(project(":platform"))
    testImplementation("org.springframework.boot:spring-boot-starter-test:2.6.6")
    compileOnly("org.projectlombok:lombok:1.18.22")
}

description = "go"
