/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("com.enpasos.muzero.java-conventions")
}

dependencies {
    implementation("com.microsoft.onnxruntime:onnxruntime:1.10.0")
    implementation("com.google.protobuf:protobuf-java:3.19.4")
    implementation("org.slf4j:slf4j-api:1.7.36")
    implementation("org.apache.commons:commons-math3:3.6.1")
    implementation("org.apache.commons:commons-csv:1.9.0")
    implementation("ai.djl:model-zoo:0.17.0-SNAPSHOT")
    implementation("ai.djl:basicdataset:0.17.0-SNAPSHOT")
    implementation("ai.djl.pytorch:pytorch-engine:0.17.0-SNAPSHOT")
    implementation("ai.djl.pytorch:pytorch-model-zoo:0.17.0-SNAPSHOT")
    implementation("ai.djl.pytorch:pytorch-native-auto:1.10.0-SNAPSHOT")
    implementation("commons-cli:commons-cli:1.5.0")
    implementation("commons-io:commons-io:2.11.0")
    implementation("org.apache.commons:commons-lang3:3.12.0")
    implementation("org.apache.commons:commons-collections4:4.4")
    runtimeOnly("org.slf4j:slf4j-simple:1.7.36")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.8.2")
    compileOnly("org.projectlombok:lombok:1.18.22")
}

description = "onnxModelGen"


