/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("com.enpasos.muzero.java-conventions")
}

dependencies {
    implementation("com.google.protobuf:protobuf-java:3.19.4")
    implementation(project(":onnxModelGen"))
    implementation("org.springframework.boot:spring-boot-starter:2.6.6")
    implementation("org.apache.commons:commons-math3:3.6.1")
    implementation("org.apache.commons:commons-csv:1.9.0")
    implementation("ai.djl:model-zoo:0.17.0-SNAPSHOT")
    implementation("ai.djl:basicdataset:0.17.0-SNAPSHOT")
    implementation("ai.djl.pytorch:pytorch-engine:0.17.0-SNAPSHOT")
    implementation("ai.djl.pytorch:pytorch-model-zoo:0.17.0-SNAPSHOT")
    implementation("ai.djl.pytorch:pytorch-native-auto:1.10.0-SNAPSHOT")
    implementation("com.google.code.gson:gson:2.9.0")
    implementation("commons-cli:commons-cli:1.4")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.13.2")
    implementation("commons-io:commons-io:2.11.0")
    implementation("org.apache.commons:commons-lang3:3.12.0")
    implementation("org.apache.commons:commons-collections4:4.4")
    implementation("ca.umontreal.iro.simul:ssj:3.3.1")
    implementation("org.jetbrains:annotations:RELEASE")
    testImplementation("org.springframework.boot:spring-boot-starter-test:2.6.6")
    compileOnly("org.projectlombok:lombok:1.18.22")
}

description = "platform"
