/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("com.enpasos.muzero.java-conventions")
}

dependencies {
    implementation(project(":tictactoe"))
    implementation("org.slf4j:slf4j-api:1.7.36")
    implementation("org.slf4j:slf4j-simple:1.7.36")
    implementation("ai.djl.pytorch:pytorch-engine:0.17.0-SNAPSHOT")
    implementation("ai.djl.pytorch:pytorch-model-zoo:0.17.0-SNAPSHOT")
    implementation("ai.djl.pytorch:pytorch-native-auto:1.10.0-SNAPSHOT")
    implementation("ai.djl:model-zoo:0.17.0-SNAPSHOT")
    implementation("ai.djl:basicdataset:0.17.0-SNAPSHOT")
    implementation("ai.djl.onnxruntime:onnxruntime-engine:0.17.0-SNAPSHOT")
    compileOnly("org.projectlombok:lombok:1.18.22")
}

description = "onnxWithRuntime"
