/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.enpasos.muzero.java-conventions")
}

dependencies {
    implementation(project(":tictactoe"))
    implementation("org.slf4j:slf4j-api:1.7.36")
    implementation("ai.djl.pytorch:pytorch-engine:0.20.0-SNAPSHOT")
    implementation("ai.djl.pytorch:pytorch-model-zoo:0.20.0-SNAPSHOT")
    implementation("ai.djl.pytorch:pytorch-native-cu116:1.12.1-SNAPSHOT")
    implementation("ai.djl:model-zoo:0.20.0-SNAPSHOT")
    implementation("ai.djl:basicdataset:0.20.0-SNAPSHOT")
    implementation("ai.djl.onnxruntime:onnxruntime-engine:0.20.0-SNAPSHOT")
    runtimeOnly("org.slf4j:slf4j-simple:1.7.36")
    compileOnly("org.projectlombok:lombok:1.18.24")
    annotationProcessor("org.projectlombok:lombok:1.18.24")
    testCompileOnly("org.projectlombok:lombok:1.18.24")
    testAnnotationProcessor("org.projectlombok:lombok:1.18.24")
}

description = "onnxWithRuntime"
