package ai.enpasos.muzero.platform.agent.d_model.service;

public enum ControllerTaskType {
    START_MULTI_MODEL, STOP_MULTI_MODEL, LOAD_LATEST_MODEL, LOAD_LATEST_MODEL_OR_CREATE_IF_NOT_EXISTING, TRAIN_MODEL_RULES, TRAIN_MODEL_POLICY_VALUE, GET_EPOCH, START_SCOPE, END_SCOPE
}
